ARG CERVER_VERSION=2.0b-29

FROM ermiry/mongoc:builder

WORKDIR /home/todo

RUN apt-get update && apt-get install -y libssl-dev

# build cerver with production flags
ARG CERVER_VERSION
RUN mkdir /opt/cerver && cd /opt/cerver \
    && wget -q --no-check-certificate https://github.com/ermiry/cerver/archive/${CERVER_VERSION}.zip \
    && unzip ${CERVER_VERSION}.zip \
    && cd cerver-${CERVER_VERSION} \
    && make -j4 && make install

RUN ldconfig

CMD ["/bin/bash"]